### ISSUE TITLE
error in file upload

### ISSUE THREAD

**Issue by jburda1** [eiryo-kawakami/wPGSA#4]
Hi, 

  I am attempting to analyze a differential gene expression data set but receive an error immediately upon submitting file for upload. Please find attached data file (.txt) containing log2 fold change data for significantly altered genes, as well as a screen shot of the error I am receiving. 

Thanks, 
## Josh Burda

Joshua E. Burda, PhD
NIH (NINDS) Ruth L. Kirschstein NRSA Postdoctoral Fellow
Paralyzed Veterans of America Research Foundation Postdoctoral Fellow
Laboratory of Michael V. Sofroniew, MD, PhD
Department of Neurobiology 
University of California, Los Angeles
Rm 504-14, Neuroscience Research Bldg.
Los Angeles, CA 90095
Laboratory: 310.206.2262 
Mobile/Text: 248.808.2003
Skype: jburda85

[HA-SCI for wPGSA.txt](https://github.com/eiryo-kawakami/wPGSA/files/404690/HA-SCI.for.wPGSA.txt)

[HA-SCI for wPGSA.xlsx](https://github.com/eiryo-kawakami/wPGSA/files/404687/HA-SCI.for.wPGSA.xlsx)

**Comment by inutano** [comment]
Hi Josh,

Thank you for your interest to our wpgsa online. I'm Tazro, a collaborator of Eiryo and I've found the issue on our web server and fixed it, so it must be working correctly now. Could you please try it again?

Thanks,
Taz

**Comment by jburda1** [comment]
Hi Taz, 

  I am still receiving an error. What  is our next step? I'd like to use your tool in a metaanalysis I am running at the moment, so the sooner the better. 

Thanks!
Josh

---

Joshua E. Burda, PhD
NIH (NINDS) Ruth L. Kirschstein NRSA Postdoctoral Fellow
Paralyzed Veterans of America Research Foundation Postdoctoral Fellow
Laboratory of Michael V. Sofroniew, MD, PhD
Department of Neurobiology 
University of California, Los Angeles
Rm 504-14, Neuroscience Research Bldg.
Los Angeles, CA 90095
Laboratory: 310.206.2262 
Mobile/Text: 248.808.2003
Skype: jburda85

**Comment by inutano** [comment]
Hi Josh,

I've looked into the error which occurs during the upload of your data, and found a bug on web application server. I've fixed it and have tested that your data "HA-SCI for wPGSA.txt" is being processed correctly. Thank you for notifying this to us!

We also suggest you to try with full gene expression data set, not only significantly altered genes, to get better result.

Let me know if you still have problems!

**Comment by jburda1** [comment]
Thanks - it seems to be working. Will let you know if I require any other assistance. 

Cheers, 
Josh

---

Joshua E. Burda, PhD
NIH (NINDS) Ruth L. Kirschstein NRSA Postdoctoral Fellow
Paralyzed Veterans of America Research Foundation Postdoctoral Fellow
Laboratory of Michael V. Sofroniew, MD, PhD
Department of Neurobiology 
University of California, Los Angeles
Rm 504-14, Neuroscience Research Bldg.
Los Angeles, CA 90095
Laboratory: 310.206.2262 
Mobile/Text: 248.808.2003
Skype: jburda85
