### ISSUE TITLE
error in file upload

### ISSUE THREAD

**Issue by kojan636** [eiryo-kawakami/wPGSA#5]
Hi,

I´d like to analyze a differential gene expression data set but receive an error soon after uploading my file. Please find the attached excel file and I´m glad if you would give me suggestions to solve this problem. 

Best wishes,
## Koji Ando

Koji Ando (安藤　康史), PhD
Uppsala University
Dept. Immunology, Genetics and Pathology, Rudbeck Laboratory
Dag Hammarskjölds Väg 20, 751 85 Uppsala, Sweden
E-mail: kando.nieve12@gmail.com 
##             koji.ando@igp.uu.se

[Book2.xlsx](https://github.com/eiryo-kawakami/wPGSA/files/507999/Book2.xlsx)

**Comment by inutano** [comment]
You should input data in tab-delimited format, not an excel format data. Please find attached file which I converted from your data. We've also fixed a bug in analysing data containing NA, so it should work now. Thank you for reporting this, let us know if you still have a problem with it.

[book2.txt](https://github.com/eiryo-kawakami/wPGSA/files/513175/book2.txt)

**Comment by kojan636** [comment]
Hi,

Unfortunately, I still have the same error message even if I upload the file you sent.

Best wishes,
Koji

**Comment by inutano** [comment]
Hi, I've checked the application log and found that another error occurred by using round bracket characters in filename. I've fixed the code so the app can handle it, could you please retry to upload your data? Thanks!

**Comment by kojan636** [comment]
Hi,
Now, I´ve succeeded in uploading! Thank you so much for your help!

**Comment by inutano** [comment]
Fantastic! My pleasure :)
